### ISSUE TITLE
Automation mail is not being sent on self hosted.

### ISSUE THREAD

**Issue by tbelbek** [khoj-ai/khoj#1067]
## Describe the bug
I configured the Resend keys according to the documentation and also the google sign-in option too on my self hosted instance. I am trying to create an automation from the existing ones and trying to run it on-demand from the "Run now" button. Then it shows the toaster on bottom right that it will send the mail in a few minutes but nothing happens. I am sure the resend configuration works because I receive the login mail without any issues. I also tried anonymous and non anonymous mode both.

## To Reproduce
Set up a self hosted instance and configure the resend and the google authentication based on the documentation.
Try to create an automation and press "Run Now".

## Screenshots
No SS but logs are here,
[logs.txt](https://github.com/user-attachments/files/18375507/logs.txt)

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [x] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version: 1.33.2 [khoj-ai/khoj:latest] 
- (also tried with the prod version since google authentication requires it.)

## Additional context
No additional comments.

**Comment by tbelbek** [comment]
And more logs,
[logs2.txt](https://github.com/user-attachments/files/18375585/logs2.txt)

**Comment by sabaimran** [comment]
Hi @tbelbek , thanks for the details. Do you mind pasting a partial stack trace directly in the issue? The file attachment doesn't seem to be loading. Any logs that you see (especially error logs) immediately after you click "run now" would be helpful.

**Comment by tbelbek** [comment]
Of course, here it is;

```
[10:35:52.948117] INFO     uvicorn.access: 172.18.0.30:44478 -   h11_impl.py:476
                           "POST                                                
                           /api/trigger/automation?automation_id                
                           =automation_254b1f08-dc92-4f5d-890c-2                
                           1912d1c2434_46bc168c4c43587378a47ff2e                
                           ce42b91 HTTP/1.1" 200                                
[10:35:52.960858] INFO     khoj.database.adapters: 🔐 Locked     __init__.py:600
                           scheduled_job_254b1f08-dc92-4f5d-890c                
                           -21912d1c2434_46bc168c4c43587378a47ff                
                           2ece42b91 to execute <function                       
                           scheduled_chat at 0x7f5620cbf640>                    
[10:35:52.964122] INFO     khoj.routers.helpers: Processing      helpers.py:1730
                           scheduled_chat: /automated_task                      
                           /research Compile a message                          
                           including: 1. A recap of major news                  
                           events from last week 2. A quick                     
                           15-minute at-home workout routine                    
                           suitable for mornings 3. An                          
                           inspirational quote for the week                     
                           ahead                                                
[10:35:53.119061] ERROR    khoj.routers.helpers: Failed to run   helpers.py:1793
                           schedule chat: , user:                               
                           tughanbelbek@gmail.com                               
                           (254b1f08-dc92-4f5d-890c-21912d1c2434                
                           ), query: /automated_task /research                  
                           Compile a message including: 1. A                    
                           recap of major news events from last                 
                           week 2. A quick 15-minute at-home                    
                           workout routine suitable for mornings                
                           3. An inspirational quote for the                    
                           week ahead                                           
[10:35:53.131308] DEBUG    khoj.database.adapters: 🔒 Run         helpers.py:193
                           <function scheduled_chat at                          
                           0x7f5620cbf640> with                                 
                           scheduled_job_254b1f08-dc92-4f5d-890c-               
                           21912d1c2434_46bc168c4c43587378a47ff2e               
                           ce42b91 process lock: 0.167 seconds                  
[10:35:53.138067] INFO     khoj.database.adapters: 🔓 Unlocked   __init__.py:616
                           scheduled_job_254b1f08-dc92-4f5d-890c                
                           -21912d1c2434_46bc168c4c43587378a47ff                
                           2ece42b91 process after executing                    
                           <function scheduled_chat at                          
                           0x7f5620cbf640> Succeeded
```
                           
Also another one;


```
[10:28:45.139392] INFO     uvicorn.access: 172.18.0.30:40372 -   h11_impl.py:476
                           "GET                                                 
                           /chat.txt?conversationId=7467c04a-47d                
                           b-4710-acf7-d4fa16a389f1&_rsc=1gu9t                  
                           HTTP/1.1" 404                                        
[10:28:45.143149] INFO     uvicorn.access: 172.18.0.30:49080 -   h11_impl.py:476
                           "GET                                                 
                           /chat.txt?conversationId=ee04961e-ee3                
                           8-493e-99d8-8c0aefc126cd&_rsc=1gu9t                  
                           HTTP/1.1" 404                                        
[10:28:45.145889] INFO     uvicorn.access: 172.18.0.30:49084 -   h11_impl.py:476
                           "GET                                                 
                           /chat.txt?conversationId=06b0476d-5ce                
                           2-4224-b738-a38f0ce5ac82&_rsc=1gu9t                  
                           HTTP/1.1" 404                                        
[10:28:45.150714] INFO     uvicorn.access: 172.18.0.30:40388 -   h11_impl.py:476
                           "GET /api/content/computer HTTP/1.1"                 
                           200                                                  
[10:28:45.156859] INFO     uvicorn.access: 172.18.0.30:49094 -   h11_impl.py:476
                           "GET                                                 
                           /chat.txt?conversationId=10143d0e-e15                
                           8-48f4-b025-89763b76520a&_rsc=1gu9t                  
                           HTTP/1.1" 404                                        
[10:28:48.373653] INFO     uvicorn.access: 172.18.0.30:49094 -   h11_impl.py:476
                           "POST                                                
                           /api/trigger/automation?automation_id                
                           =automation_254b1f08-dc92-4f5d-890c-2                
                           1912d1c2434_46bc168c4c43587378a47ff2e                
                           ce42b91 HTTP/1.1" 200                                
[10:28:48.387998] INFO     khoj.database.adapters: 🔐 Locked     __init__.py:600
                           scheduled_job_254b1f08-dc92-4f5d-890c                
                           -21912d1c2434_46bc168c4c43587378a47ff                
                           2ece42b91 to execute <function                       
                           scheduled_chat at 0x7f5620cbf640>                    
[10:28:48.392035] INFO     khoj.routers.helpers: Processing      helpers.py:1730
                           scheduled_chat: /automated_task                      
                           /research Compile a message                          
                           including: 1. A recap of major news                  
                           events from last week 2. A quick                     
                           15-minute at-home workout routine                    
                           suitable for mornings 3. An                          
                           inspirational quote for the week                     
                           ahead                                                
[10:28:48.427577] DEBUG    khoj.database.adapters: 🔒 Run         helpers.py:193
                           <function scheduled_chat at                          
                           0x7f5620cbf640> with                                 
                           scheduled_job_254b1f08-dc92-4f5d-890c-               
                           21912d1c2434_46bc168c4c43587378a47ff2e               
                           ce42b91 process lock: 0.036 seconds                  
[10:28:48.455681] INFO     khoj.database.adapters: 🔓 Unlocked   __init__.py:616
                           scheduled_job_254b1f08-dc92-4f5d-890c                
                           -21912d1c2434_46bc168c4c43587378a47ff                
                           2ece42b91 process after executing                    
                           <function scheduled_chat at                          
                           0x7f5620cbf640> Succeeded
```

**Comment by debanjum** [comment]
Hi @tbelbek, how had you setup the chat model for Khoj? We've fixed a few things in using the correct model for the automation flow. Can you verify that your Khoj is able to send automations with the latest `pre` tagged Khoj docker image? 

Note: The `pre` tagged Khoj docker images are pre-release Khoj docker images that track the latest commit on master. The default Khoj docker-compose uses the `latest` tagged Khoj docker image, which tracks the latest tagged release of Khoj.

**Comment by tbelbek** [comment]
Hello, @debanjum, I tried configuring with the api key option on the compose file and from the administration page both. But it did not work unfortunately.

I also tried with the pre image but still not working. Should I try it with a clean install?

The logs looked same to me;

[09:04:45.193795] INFO     uvicorn.access: 172.18.0.30:35004 -   h11_impl.py:476
                           "POST                                                
                           /api/trigger/automation?automation_id                
                           =automation_fe6e30c1-0482-465c-865c-7                
                           6e31ac95b8e_f488aa99882baf1ec340821ae                
                           cfacfe5 HTTP/1.1" 200                                
[09:04:45.203131] INFO     khoj.database.adapters: 🔐 Locked     __init__.py:613
                           scheduled_job_fe6e30c1-0482-465c-865c                
                           -76e31ac95b8e_f488aa99882baf1ec340821                
                           aecfacfe5 to execute <function                       
                           scheduled_chat at 0x7f7c070f1480>                    
[09:04:45.205812] INFO     khoj.routers.helpers: Processing      helpers.py:1860
                           scheduled_chat: /automated_task                      
                           Compile a message including: 1. A                    
                           recap of news from last week 2. An                   
                           at-home workout I can do before work                 
                           3. A quote to inspire me for the week                
                           ahead                                                
[09:04:45.276387] ERROR    khoj.routers.helpers: Failed to run   helpers.py:1923
                           schedule chat: , user:                               
                           tughanbelbek@gmail.com                               
                           (fe6e30c1-0482-465c-865c-76e31ac95b8e                
                           ), query: /automated_task Compile a                  
                           message including: 1. A recap of news                
                           from last week 2. An at-home workout                 
                           I can do before work 3. A quote to                   
                           inspire me for the week ahead                        
[09:04:45.280509] DEBUG    khoj.database.adapters: 🔒 Run         helpers.py:195
                           <function scheduled_chat at                          
                           0x7f7c070f1480> with                                 
                           scheduled_job_fe6e30c1-0482-465c-865c-               
                           76e31ac95b8e_f488aa99882baf1ec340821ae               
                           cfacfe5 process lock: 0.075 seconds                  
[09:04:45.293550] INFO     khoj.database.adapters: 🔓 Unlocked   __init__.py:629
                           scheduled_job_fe6e30c1-0482-465c-865c                
                           -76e31ac95b8e_f488aa99882baf1ec340821                
                           aecfacfe5 process after executing                    
                           <function scheduled_chat at                          
                           0x7f7c070f1480> Succeeded

**Comment by tbelbek** [comment]
For some reason for this log, the request was not failing but returning a 308 Permanent Redirect

```
[09:04:45.276387] ERROR    khoj.routers.helpers: Failed to run   helpers.py:1923
                           schedule chat: , user:                               
                           tughanbelbek@gmail.com                               
                           (fe6e30c1-0482-465c-865c-76e31ac95b8e                
                           ), query: /automated_task Compile a                  
                           message including: 1. A recap of news                
                           from last week 2. An at-home workout                 
                           I can do before work 3. A quote to                   
                           inspire me for the week ahead  
```

So I added the 308 Permanent Redirect code to cover that case. Now I can receive the mails perfectly. I also created a PR for that.
