### ISSUE TITLE
[FIX] Can't get to the admin panel using pip-installed khoj

### ISSUE THREAD

**Issue by raphaelventura** [khoj-ai/khoj#1123]
## Describe the bug
I'm trying to access the admin panel, but I get the CSRF bug mentioned in the [docs](https://docs.khoj.dev/get-started/setup/?server=pip&os=linux&gpu=vulkan&client=emacs&chatmodel=offline#add-chat-models), although I'm using `localhost` to access it.

Note that:
- I deleted and re-created the pgsql database in order to go through the initial configuration again and ensure my login/password were set as expected.
- Same behavior from chromium and firefox, although if I try using an empty firefox profile, I don't have this error, but instead I get a 302 code and I'm stuck on the login page!
- I had tried to use the docker images at first so maybe there is still something messing with the python install?
- I removed my firefox navigation data + cache just in case

## To Reproduce
- Install self-hosted khoj with [these parameters](https://docs.khoj.dev/get-started/setup/?server=pip&os=linux&gpu=vulkan&client=desktop&chatmodel=offline#add-chat-models)
- Go to http://localhost:42110/server/admin/, input login and password used during the first launch setup.

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [X] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [X] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [X] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]: 1.36.6

**Comment by clickbrain** [comment]
I am getting the CSRF error using the Docker install and I am using the localhost URL. Has anyone found any other fixes for this?

**Comment by fivejjs** [comment]
same here

**Comment by CHANTXU64** [comment]
Same here with Docker. Fixed by deleting container and volumes, redeploying, and reconfiguring. Works now!

**Comment by debanjum** [comment]
Hi folks, this issue has turned into a mix of multiple issues. So I'm going to break it down.

### Original Issue
I found an issue in 5a3c7b1 that was (incorrectly) requiring folks to set `KHOJ_DOMAIN` or `KHOJ_DEBUG=True`. Otherwise the login to admin panel would fail with the CSRF issue. These environment variables are not (expected to be) set by default. 

I've pushed a [fix](https://github.com/khoj-ai/khoj/commit/3fc1435cd102409e031392a446684a309f9eff26) for that issue to the mainline. If you're using the khoj docker image you can try it out by using the pre-release docker image (i.e `ghcr.io/khoj-ai/khoj:pre`) or wait for the next release (by end of this week) or set `KHOJ_DEBUG=True` in the docker-compose.yml as a mitigation until then.

### Issue 2
@lumisoft, if admin username, password is showing as invalid, you'd need to do something similar to @CHANTXU64. That is,
1. Delete your Khoj docker volume (i.e `docker volume rm khoj_khoj_db`)
2. Set the `KHOJ_ADMIN_EMAIL` and `KHOJ_ADMIN_PASSWORD` set in your `docker-compose.yml` to whatever you like 
3. Redeploy your Khoj service
4. Try login to the admin panel using the credentials set in step 2.

Admin email, password should only be set before the first (ever) run of khoj. It can only be changed by deleting the khoj db (i.e delete the `khoj_khoj_db` docker volume when setup khoj via docker) and redeploying the service with the new `KHOJ_ADMIN_EMAIL` and `KHOJ_ADMIN_PASSWORD` environment variables set before.

Thanks for the detailed bug report @raphaelventura. I'm marking this issue as resolved for now. Please feel free to reopen it if the original issue persists. 

For folks facing the invalid admin username, password issue, feel free to open a new issue to track that if you still cannot login to your admin panel after following the suggestions above.

**Comment by raphaelventura** [comment]
Reopening since the issue persists after reinstalling and launching khoj using the new embedded pgsql database.
