### ISSUE TITLE
Self-Hosted Docker can not login /server/admin

### ISSUE THREAD

**Issue by lixianwa** [khoj-ai/khoj#1152]
### Server

- [ ] Cloud (https://app.khoj.dev)
- [x] Self-Hosted Docker
- [ ] Self-Hosted Python package
- [ ] Self-Hosted source code

### Clients

- [x] Web browser
- [ ] Desktop/mobile app
- [ ] Obsidian
- [ ] Emacs
- [ ] WhatsApp

### OS

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Khoj version

1.39.0

### Describe the bug

can not login admin panel

1. input email and password
<img width="1510" alt="Image" src="https://github.com/user-attachments/assets/642b3329-2cf5-4768-8766-e21c92ace128" />

2. press login button, and then display

<img width="1508" alt="Image" src="https://github.com/user-attachments/assets/69eabaa2-81f3-44de-9f5b-ef559ed957bc" />

### Current Behavior

open /server/admin, input email and password before set in docker-compose.yml, then login, but can not login

### Expected Behavior

login admin 

### Reproduction Steps

login admin panel

### Additional Information

server log

[khoj_log.txt](https://github.com/user-attachments/files/19619671/khoj_log.txt)

**Comment by debanjum** [comment]
Hey @lixianwa Please try the following to see if it fixes your issue to login to the admin panel:
1. Delete your Khoj DB. (i.e delete the `khoj_db` docker volume via CLI or the Docker desktop app on your Mac)
2. Set environment variable `KHOJ_DEBUG=True` in your `docker-compose.yml`
3. Restart the Khoj docker service and try login with your admin email and admin password

**Comment by debanjum** [comment]
I've pushed some [fixes](https://github.com/khoj-ai/khoj/commit/3fc1435cd102409e031392a446684a309f9eff26) that should (hopefully) resolve this issue by the next release. You can try the fixes now by using the pre-release tagged Khoj docker image (i.e change `image` to `ghcr.io/khoj-ai/khoj:pre` in your docker-compose.yml) or wait for the next release (that should be out by the end of this week).

**Comment by lixianwa** [comment]
> Hey @lixianwa Please try the following to see if it fixes your issue to login to the admin panel:
> 1. Delete your Khoj DB. (i.e delete the `khoj_db` docker volume via CLI or the Docker desktop app on your Mac)
> 2. Set environment variable `KHOJ_DEBUG=True` in your `docker-compose.yml`
> 3. Restart the Khoj docker service and try login with your admin email and admin password

Hi，@debanjum， thank you for your reply！I did it according to your method, and the problem has been solved. But I don't know why deleting db volume data didn't work before. This time, deleting db volume data and opening debug at the same time worked.

**Comment by AndreC10002** [comment]
Having exactly the same problem with Docker, including with the 'ghcr.io/khoj-ai/khoj:pre' image. My vars are set on docker-compose.yml as simple as they can be under 'server':

      - KHOJ_ADMIN_EMAIL=admin
      - KHOJ_ADMIN_PASSWORD=admin

and I still can't log in to /server/admin

Help would be greatly appreciated.
Thank you.
